SCRIPT_DIR=$(realpath $(dirname "$(readlink -f "${BASH_SOURCE[0]}")"))

IREE_BUILD_DIR=$SCRIPT_DIR/build
IREE_BUILD_COMPILER_DIR=$IREE_BUILD_DIR/compiler
IREE_BUILD_COMPILER_BIN_DIR=$IREE_BUILD_COMPILER_DIR/install/bin
IREE_BUILD_COMPILER_LIB_DIR=$IREE_BUILD_COMPILER_DIR/lib

DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$IREE_BUILD_COMPILER_LIB_DIR

PATH=$PATH:$IREE_BUILD_COMPILER_BIN_DIR

source $IREE_BUILD_COMPILER_DIR/.env
